# Generated by Django 5.1.5 on 2025-01-27 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_user(apps, schema_editor):
    # Get the User model
    User = apps.get_model(settings.AUTH_USER_MODEL)
    # Get the Order model
    Order = apps.get_model('shop', 'Order')
    # Create or get a placeholder user (adjust as needed)
    placeholder_user, _ = User.objects.get_or_create(username='placeholder', defaults={'password': 'placeholder'})
    # Update existing orders with the placeholder user
    Order.objects.filter(user=None).update(user=placeholder_user)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cupcake',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                null=True,  # Temporarily allow null values
            ),
        ),
        migrations.RunPython(set_default_user),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                null=False,  # Make the field non-nullable after default values are set
            ),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cupcake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cupcake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.cupcake'),
        ),
    ]
